### ISSUE TITLE
Feature request - show current running PID's of Node processes

### ISSUE THREAD

**Issue by KromDaniel** [gonenduk/late-inspect#1]
This script accepts PID as the argument, finding PID might not be easy task for everybody, you might want to add the ability to suggest list of all running node js processes.

usage example

`late-inspect --lookup`
Will print

[pid]             [script path]    [node args]            [script args]      
  23               /my/script.js       --expose-gc       --my-custom-flag=6
  24               /my/script.js     --inspect             --my-custom-flag=7 (Already with inspect flag, show in different color?)
  27               /my/script2.js                               --my-custom-flag=98

Thanks!

**Comment by gonenduk** [comment]
Done. Published version 1.1.0
